mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: sql839599
  db: ame
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:
minio:
  endpoint: 49.232.167.227:30090
  bucket: ame-test
  tls: false
  access_key: minioadmin
  secret_key: minioadmin
