// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/m01i0ng/go-skeleton/app"
	"github.com/m01i0ng/go-skeleton/internal/config"
	"github.com/m01i0ng/go-skeleton/internal/db"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	client, err := db.NewRedis(configConfig)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.NewMysql(configConfig)
	if err != nil {
		return nil, err
	}
	minioClient, err := db.NewMinio(configConfig)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(client, sqlDB, minioClient)
	return appApp, nil
}
